### ISSUE TITLE
New wallet import mnemonic Dapp cannot get rpc data normally

### ISSUE THREAD

**Issue by zhb666** [ckb-js/nexus#104]
![image](https://user-images.githubusercontent.com/18475950/223052321-faaf6227-8a1b-4a89-8ff4-598c6c9d5256.png)
The wallet has been installed but no relevant data is returned ，suspected to be caused by watchtower

**Comment by homura** [comment]
this bug is fixed by the new watchtower, can you check it again with the latest main branch build

**Comment by zhb666** [comment]
> this bug is fixed by the new watchtower, can you check it again with the latest main branch build

It has been verified that there is no problem
