### ISSUE TITLE
Review Nexus MVP demo

### ISSUE THREAD

**Issue by homura** [ckb-js/nexus#118]
Review the features of https://github.com/zhangyouxin/demo-nexus

- [x] Address book
- [x] Transferring CKB
- [x] Receiving CKB

**Comment by zhb666** [comment]
- claim test CKB from faucet and check the receiving book
  - transferring CKB to derived address
  - compared with Neuron's address book
  - reviewed how nexus-demo assembling transaction, it is pretty

**Comment by zhb666** [comment]
Transfer to a random address. Format error exception
![image](https://user-images.githubusercontent.com/18475950/224921028-0029c20a-7929-47ec-8973-2bbec1c16fb9.png)

**Comment by zhb666** [comment]
修复 MVP demo cell不能正常上链的问题https://github.com/zhangyouxin/demo-nexus/commit/c16112f7bbf95fd355baf88cf403a1ba8b9ee3e6

**Comment by homura** [comment]
it is finished?
