### ISSUE TITLE
[Feature Request] Create an Account Or Import Mnemonics

### ISSUE THREAD

**Issue by zhangyouxin** [ckb-js/nexus#12]
### Motivation

As a Nexus wallet user, the first thing I want to do is to create/import an account, so that I can get access to other wallet functionalities.

### Description

If I was a new ckb user, I would like to create a new account, so I need a "Create Account" button, and the wallet should prompt a list of randomly generated mnemonics.

<img width="1353" alt="image" src="https://user-images.githubusercontent.com/3870972/209527197-c7165459-a082-43b3-958a-391a5322d708.png">

After the user had created an account, the root address should be generated by the [key derivation rule](https://github.com/ckb-js/nexus/blob/pre-design/docs/design.md#key-derivation).

Or if the user had imported an account, the root address should be generated, and the used addresses should be discovered by a similar rule in [bip-44](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki#account-discovery).

### Privacy

The mnemonics should be encrypted and stored with [web3 secret storage](https://github.com/ethereum/wiki/wiki/Web3-Secret-Storage-Definition).

### Test vectors

//tbd

**Comment by homura** [comment]
implemented
