### ISSUE TITLE
Nervos DAO dApp operation document

### ISSUE THREAD

**Issue by zhb666** [ckb-js/nexus#125]

**Comment by zhb666** [comment]
[Reference documents](https://github.com/zhb666/Nervos-DAO/blob/main/docs/localNodeTutorial.md)

**Comment by zhangyouxin** [comment]
### 文档修改意见

- 文件名 “****Ne本地节点交互配置****” 需要修改
- 相关 CKB node 运行说明的链接不对
 <img width="400" alt="image" src="https://user-images.githubusercontent.com/3870972/226348411-ec2a0bbd-f776-4ae6-bda2-1ea1e230fec0.png">

- `genesis_epoch_length` 建议直接改为 1
- `permanent_difficulty_in_dummy` 默认为 true 不需要修改
- 缺少对 Nexus Wallet 修改 code 来切换到 devnet 的相关说明
- “**查找钱包地址**” 功能说明可以移除
- “**转账到钱包**” 建议直接在 `spec/dev.toml` 里直接给某个地址发钱
- 缺少 devnet 运行挖矿程序相关说明
- 注意检查 code block 的语言类型，例如这种用 ts 语法是不对的
<img width="243" alt="image" src="https://user-images.githubusercontent.com/3870972/226350945-3ff26a00-863f-4a34-b94c-89afdfbad3d9.png">

- “还需要替换 depGroup 中的 outPoint.txHash” 是不需要的
- “具体资料可以参考” 可以不用 header，可以专门列一个 reference list 
- 排版需要更好看一点
