### ISSUE TITLE
Documentation for unlocking by another script

### ISSUE THREAD

**Issue by homura** [ckb-js/nexus#132]
Since not all cells can be fully controlled by a single party, a case in point is the name service, which generally has an expiration date and the owner only has control over it for a given duration, we need a document that describes how Nexus works with this scenario

**Comment by zhangyouxin** [comment]
Is there any reference links for the scenario？ such as https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0039-cheque/0039-cheque.md

**Comment by homura** [comment]
> Is there any reference links for the scenario？ such as [nervosnetwork/rfcs@master/rfcs/0039-cheque/0039-cheque.md](https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0039-cheque/0039-cheque.md?rgh-link-date=2023-03-20T14%3A33%3A40Z)

Right, the `cheque` script is a use case for unlocking by another script
