### ISSUE TITLE
Review Nervos DAO demo

### ISSUE THREAD

**Issue by homura** [ckb-js/nexus#133]
https://github.com/zhb666/Nervos-DAO

- [ ] tested locally, according to the [documentation](https://github.com/ckb-js/nexus/issues/125)
- [ ] code
- [ ] testnet

**Comment by zhangyouxin** [comment]
some comments on Docs： https://github.com/ckb-js/nexus/issues/125#issuecomment-1476225859

**Comment by zhangyouxin** [comment]
code review: https://github.com/zhb666/Nervos-DAO/issues/3
