### ISSUE TITLE
Cannot read properties codeHash

### ISSUE THREAD

**Issue by gpBlockchain** [ckb-js/nexus#137]
ccommit:[abadb89](https://github.com/ckb-js/nexus/commit/abadb896648b0587254b662535dd26d764f02540)
### step
```
const ckb = await window.ckb.enable()
ckb.fullOwnership.signData({data:"0x1212"})
```
<img width="758" alt="image" src="https://user-images.githubusercontent.com/32102187/226509436-a4e0bd18-46dc-4581-bd62-d2ac5495021f.png">

**Comment by homura** [comment]
`signData` needs [two params](https://github.com/ckb-js/nexus/blob/main/docs/rpc.md#wallet_fullownership_signdata), you are missing a `lock` in the params of your request, but the error message is so. But this error message is really unfriendly, we'll improve [this](https://github.com/ckb-js/nexus/pull/110)
