### ISSUE TITLE
ico is wrong

### ISSUE THREAD

**Issue by gpBlockchain** [ckb-js/nexus#148]
connect url:https://playwright.dev/
nexus wallet ico link:"https://playwright.dev/favicon.ico"
<img width="918" alt="image" src="https://user-images.githubusercontent.com/32102187/227465953-6a1b7c99-81fc-4a50-b698-325cf4558aef.png">
playwright ico link:https://playwright.dev/img/playwright-logo.svg
<img width="1340" alt="image" src="https://user-images.githubusercontent.com/32102187/227465998-2e8c3a3c-e407-40a1-99be-95a0592529ba.png">

**Comment by homura** [comment]
will be resolved by https://github.com/ckb-js/nexus/pull/122
