### ISSUE TITLE
[wallet_fullOwnership_getLiveCells]What cursor means in the field before:

### ISSUE THREAD

**Issue by gpBlockchain** [ckb-js/nexus#163]
- nexus version:https://github.com/ckb-js/nexus/commit/ba5923525ac7706e5e14834b9c68b4652f4a83db
### example
What does 22 mean

<img width="739" alt="image" src="https://user-images.githubusercontent.com/32102187/228170257-1a53ee21-c571-4916-8a25-d286339c53d1.png">

**Comment by zhangyouxin** [comment]
This field is an internal index of derived lock, which should not be exposed to developers, we will refactor this in the future.
