### ISSUE TITLE
Ask CKB Indexer team for chained transaction 

### ISSUE THREAD

**Issue by homura** [ckb-js/nexus#259]
We found that if chained tx is supported in SDK, a similar logic would need to be implemented in each SDK to create a space for these pending cells, and we are considering whether it would make more sense for the CKB indexer itself to implement this instead of all SDKs. We should ask the CKB Indexer team for more information

_Originally posted by @homura in https://github.com/ckb-js/nexus/issues/224#issuecomment-1519309530_

**Comment by zhangyouxin** [comment]
There are already some conclusions, head over to https://github.com/ckb-js/nexus/issues/224#issuecomment-1521975311
