### ISSUE TITLE
[Feature Request] show transaction fee

### ISSUE THREAD

**Issue by zhangyouxin** [ckb-js/nexus#261]
## Description

When I am using Nexus to sign a transaction, for example, a transaction to claim cheque, I don't know how much transaction fee I have paid.

<img width="443" alt="image" src="https://user-images.githubusercontent.com/3870972/234036485-496c7c8f-281f-479e-a969-28caefcaedf2.png">

So, if the sign transaction popup shows how much transaction fee I need to pay, that will help me a lot. Here is a example of Metamask:

<img width="350" alt="image" src="https://user-images.githubusercontent.com/3870972/234037899-0c5c01d9-dfef-4897-aff5-fd01b9f72b34.png">

**Comment by homura** [comment]
We'll reopen the issue when we find a better time to return to resume the Nexus developing
