### ISSUE TITLE
[Feature Request] Allow user define contract to be signed

### ISSUE THREAD

**Issue by zhangyouxin** [ckb-js/nexus#262]
## Description

Currently, Nexus Wallet can only sign secp256k1blake160 lock cell inputs. This becomes very inconvenient if some contract requires a user signature on contract lock, otherwise contracts must be designed to have a `custody` unlock mode to use Nexus.

Let's take the `cheque` contract as an example, cheque cell has two unlock modes, claim and withdraw, and `claim` has two rules, user can pick one to unlock the cheque cell:
1. receiver signature on cheque cell
2. receive cell in tx inputs (custody mode)

Now that Nexus supports option 2, but that way, the receiver address must have some CKBytes balance to claim SUDT, if Nexus can sign the cheque cell using the receiver lock private key, the problem will be solved.

## How could the solution be like

```
window.ckb.request({ method: "wallet_allow_sign_contract", params: [{
    codeHash: <cheque_code_hash>,
    hashType: <cheque_code_hash>,
    argsRange: <args_range_of_signing_lock>,// should be [0, 20] for cheque to find receiver lock
   // another example: as for omnilock owner mode, arsRange should be [1, 21]
  }] 
})
```

For the params:
- codeHash: code hash of contract
- hashType: how to locate the contract in cellDep
- arsRange: Nexus does not know which private key to use to sign the contract cell, `wallet_allow_sign_contract` rpc need to tell nexus how to do that, this parameter indicates a range to retreive from `args` of contract cell lock.

Just like Ethereum Dapp requires user to allocate contract allowance, then user will be prompted to allow nexus to sign cheque, by user inputs correct password, Nexus wiil add the contract info to whiteList. Then when user requests `wallet_fullOwenrship_signTransaction`, cheque cells will be signed if the receiver lock is controlled by the wallet.

Example Dapp Flow：

1. end user operates on Dapp page
2. end user fires a transaction to claim a cheque
3. Dapp request `wallet_allow_sign_contract`
4. end user enter password to allow Nexus sign cheque cell (if cheque contranct is already in whitelist, skip this step)
5. Dapp request `wallet_fullOwenrship_signTransaction`
6. end user signs transaction (better tell user which cells will be signed)
7. done

**Comment by homura** [comment]
the `cheque` lock may just be a corner case, there are many signing way in CKB, e.g. Omnilock's auth flag, PW lock's keccak + secp256k1, if we want to support more signature methods, we may need to consider more
