### ISSUE TITLE
Nervos DAO dApp with mock `InjectedCkb`

### ISSUE THREAD

**Issue by homura** [ckb-js/nexus#36]

**Comment by homura** [comment]
A minimal implementation here https://github.com/zhb666/Nervos-DAO, but only the deposit is mocked, and the example will be updated continuously

**Comment by zhb666** [comment]
## Dapp page design
### 1. Deposit cannot be operated without connecting Nexus wallet
<img width="1118" alt="image" src="https://user-images.githubusercontent.com/18475950/216498131-0b0b2c27-7daf-4d4d-87bd-c39c55a17387.png">

### 2.Deposit can be operated by connecting Nexus wallet
<img width="1125" alt="image" src="https://user-images.githubusercontent.com/18475950/216498560-5e554133-0efc-466e-87d7-0cce17bd4951.png">

### 3.After entering the amount, send the transaction to get the Hash
<img width="1120" alt="image" src="https://user-images.githubusercontent.com/18475950/216499373-430164c9-ce24-493d-b827-8d325be15bf2.png">

### 4.Click the Transaction Hash link to view the results
<img width="1118" alt="image" src="https://user-images.githubusercontent.com/18475950/216499536-87f6e907-7960-4538-8e57-0ab1312c28c3.png">

### 5.Jump to the blockchain browser to check whether the data is correct
<img width="1678" alt="image" src="https://user-images.githubusercontent.com/18475950/216499633-102f6eee-a6c0-4db4-90d8-be93ddbae808.png">

**Comment by homura** [comment]
where can we preview it?

**Comment by zhb666** [comment]
> where can we preview it online?

[https://nervos-dao-179e.vercel.app/](https://nervos-dao-179e.vercel.app/)
