### ISSUE TITLE
[e2e] list test cases and negotiate element locators

### ISSUE THREAD

**Issue by homura** [ckb-js/nexus#59]

**Comment by gpBlockchain** [comment]
Regarding element location, I can use the testing-library library to locate it, and if it's really hard to locate then I will add a test-data-id tag.

### what is `testing-library`？
Locate various DOM nodes on the page just like a user would, avoiding the implementation details of components.

### How to locate elements after using testing-library?
<img width="1465" alt="image" src="https://user-images.githubusercontent.com/32102187/215734239-d26bd7d5-3dc4-4dd4-9035-84757e9fcde7.png">

### example:importWallet code 
<img width="413" alt="image" src="https://user-images.githubusercontent.com/32102187/215735680-cab45175-2518-47b7-836e-b29d7fce2a48.png">

https://user-images.githubusercontent.com/32102187/215741090-b76917e0-112b-40e6-8776-42c819e7f30e.mov

### shortcoming
1. unable to read data on web page ,when you need to read web page data, you must use xpath or select
2. [pptr-testing-library](https://github.com/testing-library/pptr-testing-library) only updated until 2021

**Comment by IronLu233** [comment]
Note: I use the WIP design for these cases. Some changes may occur in the future
The anchor use [HTML data attributes](https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes).
Here is a example
```html
<button data-test-id="createWallet">Create a wallet</button>
```
and there sometimes also have other data-test-* attributes when the page need provide more information to E2E test program.
# Flow 1 create/import wallet
##  Page 1: New  to nexus
![image](https://user-images.githubusercontent.com/20639676/216249239-35c08bf8-6592-454c-9f96-a4e6dd26ef32.png)

Anchors:
- test-id: `createWallet` on "Create a wallet button"
- test-id: `importWallet` on "Import wallet button"

## Page 2: get started
![image](https://user-images.githubusercontent.com/20639676/216273268-ade294b3-ff6c-4cbd-9c1e-009be9f49951.png)
Anchors:
- test-id: `getStarted`, the "get started" button

## Page 3 create account
![image](https://user-images.githubusercontent.com/20639676/216276401-5172aa77-4fd2-4761-9500-6147cee020e5.png)
Anchors:
- test-id: `userName`, the "user name" input
- test-id: `back`，the "back button"
- test-id: `next`, the "next" button

## Page 4 create password

![image](https://user-images.githubusercontent.com/20639676/216277231-18e6431d-6ed8-4953-8af5-90b4b76a9cad.png)


Anchors:
- test-id: `password`, the password input
- test-id: `confirm-password`, the confirm password input
- test-id: `aggreeTermsOfUse` the checkbox item
- test-id: `back`，the "back button"
- test-id: `next`, the "next" button

## Page 5, wallet generation seed
![image](https://user-images.githubusercontent.com/20639676/216277491-d3c22885-b4af-4c60-b13e-0669b7b4e244.png)

Anchors:
- test-id: `seed`, the seed input
- test-id: `copyToClipboard`, the copy to clipboard button
- test-id: `back`，the "back button"
- test-id: `next`, the "next" button

## Page 6, confirm seed（TBD）
![image](https://user-images.githubusercontent.com/20639676/216279820-b7e084e1-f78c-4959-b172-da6cdc745a51.png)

Anchors:
- test-id: ``
- test-id: `back`，the "back button"
- test-id: `next`, the "next" button

## Page6, all down, conguratulations
![image](https://user-images.githubusercontent.com/20639676/216280789-c889eabf-9d2a-4e4c-90da-5ea34555dfdc.png)

Anchors:
- test-id: `done`, the "all done" button

## Page 8, import wallet 
![image](https://user-images.githubusercontent.com/20639676/216285983-1884b2a1-cf30-4068-8198-ddb05dcc62d4.png)
- test-id: `seed-1`, `seed-2`, ... `seed-n` the seed input for the recovery, n means the index
- test-id: `back`，the "back button"
- test-id: `next`, the "next" button

# Flow 2, popup
## Page 1 popup home window

![image](https://user-images.githubusercontent.com/20639676/216287079-7a8912a2-8cab-41d2-b298-792cefaefaa8.png)

Anchors:
- data-test-id: 'connectedStatus' connected or not connted text. with boolean attr `test-connected` can get the status
- test-id: 'whitelistSites', the whitelist sites page entry
- test-id: 'network', the network page entry

## Page2 whitelist sites
![image](https://user-images.githubusercontent.com/20639676/216288716-2aaa8314-4154-444c-8bb1-56bc98d438a9.png)
Anchors:
- data-test-id: 'back' the back button in top left of page
- test-id: `search`: the search input for network
- test-id: networkList: network list
- test-id: networkURL-i: the network item URL in the list, i means index
- test-id: networkURLDelete-i: the delete network action button, index

**Comment by IronLu233** [comment]
# Popup
## Home
![image](https://user-images.githubusercontent.com/20639676/216502516-a25b18a2-6848-4f77-885f-bb3dd7270d96.png)

Anchors:
- test-id: `connectedStatus`, `connectStatusText`, `connectStatusIndicator`, the DApp connect status of wallet. text is "connected"/"disconnected" plain text, indicator is the green/gray filled circle for indicating
- test-id: `whilteListSites`, a button, the entry of Whitelist Sites
- test-id: `network`, a button, the entry of network config

## Whitelist sites
![image](https://user-images.githubusercontent.com/20639676/216503201-fc3e3c02-c134-4c9e-b591-48e8a3bce712.png)
Anchors:
- test-id: `back`, the back button on top left
- test-id: `websiteSearch`, the search input of website
- test-id: `websiteList`, the website list container item
- test-id: `website#n`  the website nth item
- test-id: `website.text#n`, the website nth item URL text
- text-id: `website.delete#n`, the website nth item's delete button

## networks

![image](https://user-images.githubusercontent.com/20639676/216505494-f0c24b81-11e5-4bd8-bfeb-d6d988ce6e94.png)

Anchors:
- test-id: `networkRadioGroup`: the radio group of current network
- test-id: `networkRadio#n`: the radio item of network, an extra `test-network-id` will be provided
- test-id: `networkRadio.name#n`: the network name of radio
- test-id: `addNetwork`:  go to add network button

## Add network

![image](https://user-images.githubusercontent.com/20639676/216514138-c6e2e74d-a47c-4f74-b7f3-95317978142c.png)
Anchors:
- test-id: `name` the network name input
- test-id: `url`
- test-id: 'add' the add network button
- test-id: 'back' back to home

**Comment by IronLu233** [comment]
# Dialog
## Sign message
![image](https://user-images.githubusercontent.com/20639676/216528976-3efbb40b-9df7-49cc-9041-7e0a54bad944.png)
Anchors:
- test-id: `reject`, the rejrect button
- test-id: `sign`, the sign button
- test-id: `password`, the password input
- test-id: `submitPassword`, the submit password button
- test-id: `url`, the requester url
- tes-tid: `message`, the message for sigining

## Grant 

Anchors:
- test-id: `grant` the grant button
- test-id: `reject` the reject button

## Sign transaction (TBD)
