### ISSUE TITLE
Message bridge for Nexus

### ISSUE THREAD

**Issue by homura** [ckb-js/nexus#6]
**Is your feature request related to a problem? Please describe.**

The injected CKB Provider will communicate with the Nexus, so a message bridge (wrapper) is required for Nexus. This bridge should 

- webpage <-> content script
- content script <-> background script
- background script <-> extension UI, e.g. `chrome.window` created window, popup.

For the CKB Provider, it may act as an RPC client, so we also need to make the bridge simply adaptable to server-client mode

```js
// perhaps the CKB provider will be like this
await window.ckb.nexus.getUnusedLocks()
await window.ckb.nexus.getCells()

// or act as RPC client
await window.ckb.nexus.request({
  method: 'wallet_getUnusedLocks',
  params: []
})
await window.ckb.nexus.request({
  method: 'wallet_getCells',
  params: []
})
```

**Additional context**

[webext-bridge](https://github.com/zikaari/webext-bridge) looks good, but webext-bridge seems not supported for injected script, maybe we can enhance it

[chomex](https://github.com/otiai10/chomex) offers server-client functionality, we can also have a look to check if we can implement it based on

**Comment by homura** [comment]
hi, @zhangyouxin any update for this issue?

**Comment by zhangyouxin** [comment]
## setup a develop env

### 1.create a repo with react and typescript, create necessary files according to [chrome extension docs](https://developer.chrome.com/docs/extensions/mv3/getstarted/extensions-101/)

https://github.com/zhangyouxin/chrome-extension-learn 

### 2.try inject some javascript file to webpage

contentScript.js
```javascript
(function injectCustomJs() {
  console.log("injectCustomJs");
  const jsPath = "inject.js";
  var temp = document.createElement("script");
  temp.setAttribute("type", "text/javascript");
  const path = chrome.runtime.getURL(jsPath);
  console.log("runtime inject.js path:", path);
  // TODO chrome extension 无法加载本地文件
  temp.setAttribute("src", path);
  document.body.appendChild(temp);
})()
``` 

<img width="624" alt="image" src="https://user-images.githubusercontent.com/3870972/209281001-279897a7-9676-4292-91e7-d927ca6c31e8.png">


### 3.try send message from client to router using chomex

background.ts
```ts
import {Router, Model, Types} from 'chomex';
// Define your model
class User extends Model {
  static schema = {
    name: Types.string.isRequired,
    age:  Types.number,
  }
}
const router = new Router();
// Define your routes
router.on("/users/create", message => {
  console.log('====================================');
  console.log('user create,',message);
  console.log('====================================');
  const obj = message.user;
  const user = User.new(obj).save();
  return user;
});

chrome.runtime.onMessage.addListener(router.listener());
```

popup.tsx
```tsx
    <button
      onClick={() => {
        const client = new Client(chrome.runtime);
        client.message("/users/create").then((response) => {
            console.log(response);
        });
      }}
    >
      send message
    </button>
```

<img width="1207" alt="image" src="https://user-images.githubusercontent.com/3870972/209281709-12f85adf-b649-414d-92af-3d9ea77909e4.png">
