### ISSUE TITLE
CKB Wallet Demo dApp

### ISSUE THREAD

**Issue by homura** [ckb-js/nexus#83]
To demonstrate how Nexus works with a dApp, we had plans to create a Nervos DAO dApp [demo](https://github.com/zhb666/Nervos-DAO), however, we found this demo may still be a bit complicated for newcomers, as it requires some knowledge about Nervos DAO, so we're planning to make another demo for CKB wallet.

This demo should have the following features

- UTxO style wallet - an address is only used once
- Show the total capacity owned by the current wallet
- Transfer CKB
- Receive CKB

**Comment by homura** [comment]
@zhangyouxin can you update this issue?

**Comment by zhangyouxin** [comment]
> @zhangyouxin can you update this issue?

The demo website is here: https://demo-nexus.vercel.app/
It supports:
 - connect wallet
 - an address is only used once
 - Show the **FULL OWNERSHIP** cells and total capacity owned by the current wallet 
 - Transfer CKB
 - Receive CKB

To use this app, user should download the chrome-extesion nexus wallet here: https://github.com/zhangyouxin/demo-nexus/releases/tag/0.0.2
Project repository: https://github.com/zhangyouxin/demo-nexus
